name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia_version: ['1.0', '1.4', '1.5']
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia_version }}
      - name: "Run tests"
        uses: julia-actions/julia-runtest@master
        if: matrix.julia_version != '1.0'
      - name: "Run tests (Julia v1.0)"
        run: |
          julia -e 'using Pkg; Pkg.activate("test"); Pkg.develop(PackageSpec(path="."))'
          julia --color=yes --check-bounds=yes --project=test test/runtests.jl
        # XXX: Julia 1.0 does not use the Project.toml in `tests` directory.
        if: matrix.julia_version == '1.0'
